CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, age INTEGER);
CREATE TABLE projects (id INTEGER PRIMARY KEY, category TEXT, funding_goal INTEGER,start_date DATE, end_date DATE);
CREATE TABLE pledges (id INTEGER PRIMARY KEY, amount INTEGER,user_id INTEGER FOREIGN KEY, project_id INTEGER FOREIGN KEY);